spring.application.name: spring-data-service

server.port: 8081

management.server.port: 8082

spring.data.cassandra:
  keyspace-name: "hr"
  username: WtOORsNrxiKfILOHWknbepyx
  password: vau6c_M_Hk+mvBpPBTFJaUEjOTqAXvQyEcbIk0zTyGDpYIM7rdLTHpeYxgdEr4qXiDbHDLeJ+7q7JHNSWPcFXjhvFRwSQpjPwLUIaF_QekOAiBYlhWo3ov6h-O.zu6ZZ
  # Create the schema on the fly if it doesn't exist

  # Increase timeouts when connecting to Astra from a dev workstation
  request:
    timeout: 100000s
  connection:
    connect-timeout: 10000s
    init-query-timeout: 100000s
cassandra:
  keyspace: showcase

datastax.astra:
  secure-connect-bundle: secure-connect-hr.zip
  
  logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE